// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AllSeleniumTestsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void gamesPublishersNews() {
    // Test name: games->Publishers->News
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | click | linkText=Games | 
    driver.findElement(By.linkText("Games")).click();
    // 3 | click | css=.card-deck:nth-child(3) > .card:nth-child(2) .btn | 
    driver.findElement(By.cssSelector(".card-deck:nth-child(3) > .card:nth-child(2) .btn")).click();
    // 4 | click | linkText=Electronic Arts | 
    driver.findElement(By.linkText("Electronic Arts")).click();
    // 5 | click | linkText=See More | 
    driver.findElement(By.linkText("See More")).click();
    // 6 | click | linkText=See More | 
    driver.findElement(By.linkText("See More")).click();
    // 7 | click | css=.media:nth-child(1) a > .mt-0 | 
    driver.findElement(By.cssSelector(".media:nth-child(1) a > .mt-0")).click();
  }
  @Test
  public void gamesPublisherNews2() {
    // Test name: games->Publisher->News  2
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | click | linkText=Games | 
    driver.findElement(By.linkText("Games")).click();
    // 3 | click | linkText=See More | 
    driver.findElement(By.linkText("See More")).click();
    // 4 | click | linkText=Rockstar Games | 
    driver.findElement(By.linkText("Rockstar Games")).click();
    // 5 | click | css=.card:nth-child(4) .btn | 
    driver.findElement(By.cssSelector(".card:nth-child(4) .btn")).click();
    // 6 | click | css=.media:nth-child(3) a > .mt-0 | 
    driver.findElement(By.cssSelector(".media:nth-child(3) a > .mt-0")).click();
  }
  @Test
  public void wishlistAddThenRemoveFirstGameOnGamesMustLOGINFirst() {
    // Test name: wishlist Add Then Remove First Game On Games, Must LOGIN First
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | click | linkText=Games | 
    driver.findElement(By.linkText("Games")).click();
    // 3 | click | css=.card-deck:nth-child(3) > .card:nth-child(1) .card-img-top | 
    driver.findElement(By.cssSelector(".card-deck:nth-child(3) > .card:nth-child(1) .card-img-top")).click();
    // 4 | click | css=.btn-secondary | 
    driver.findElement(By.cssSelector(".btn-secondary")).click();
    // 5 | verifyElementPresent | css=.btn-secondary | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".btn-secondary"));
      assert(elements.size() > 0);
    }
    // 6 | click | linkText=Wishlist | 
    driver.findElement(By.linkText("Wishlist")).click();
    // 7 | click | linkText=Remove | 
    driver.findElement(By.linkText("Remove")).click();
  }
  @Test
  public void darkModeSwitchingWhenLoggedIn() {
    // Test name: dark Mode Switching When Logged In
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | click | css=.toggle-on | 
    driver.findElement(By.cssSelector(".toggle-on")).click();
    // 3 | click | css=.toggle-off | 
    driver.findElement(By.cssSelector(".toggle-off")).click();
    // 4 | click | css=.toggle-on | 
    driver.findElement(By.cssSelector(".toggle-on")).click();
    // 5 | click | css=.toggle-off | 
    driver.findElement(By.cssSelector(".toggle-off")).click();
    // 6 | click | css=.toggle-on | 
    driver.findElement(By.cssSelector(".toggle-on")).click();
    // 7 | click | css=.toggle-off | 
    driver.findElement(By.cssSelector(".toggle-off")).click();
  }
  @Test
  public void developersGamesDevolopers() {
    // Test name: developers->Games->Devolopers
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | click | linkText=Developers | 
    driver.findElement(By.linkText("Developers")).click();
    // 3 | click | css=.card-deck:nth-child(3) > .card:nth-child(1) .card-img-top | 
    driver.findElement(By.cssSelector(".card-deck:nth-child(3) > .card:nth-child(1) .card-img-top")).click();
    // 4 | click | linkText=See More | 
    driver.findElement(By.linkText("See More")).click();
    // 5 | click | linkText=Feral Interactive | 
    driver.findElement(By.linkText("Feral Interactive")).click();
  }
  @Test
  public void clickAllTabsWhenLoggedOut() {
    // Test name: click All Tabs When Logged Out
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | click | linkText=GameDB | 
    driver.findElement(By.linkText("GameDB")).click();
    // 3 | click | linkText=Home | 
    driver.findElement(By.linkText("Home")).click();
    // 4 | click | linkText=Developers | 
    driver.findElement(By.linkText("Developers")).click();
    // 5 | click | linkText=Publishers | 
    driver.findElement(By.linkText("Publishers")).click();
    // 6 | click | linkText=About | 
    driver.findElement(By.linkText("About")).click();
    // 7 | click | linkText=News | 
    driver.findElement(By.linkText("News")).click();
    // 8 | click | linkText=Games | 
    driver.findElement(By.linkText("Games")).click();
  }
  @Test
  public void clickAllTabsWhenLoggedIn() {
    // Test name: click All Tabs When Logged In
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 973x777 | 
    driver.manage().window().setSize(new Dimension(973, 777));
    // 3 | click | linkText=GameDB | 
    driver.findElement(By.linkText("GameDB")).click();
    // 4 | click | linkText=Home | 
    driver.findElement(By.linkText("Home")).click();
    // 5 | click | linkText=Games | 
    driver.findElement(By.linkText("Games")).click();
    // 6 | click | linkText=Publishers | 
    driver.findElement(By.linkText("Publishers")).click();
    // 7 | click | linkText=Wishlist | 
    driver.findElement(By.linkText("Wishlist")).click();
    // 8 | click | linkText=About | 
    driver.findElement(By.linkText("About")).click();
    // 9 | click | linkText=News | 
    driver.findElement(By.linkText("News")).click();
  }
  @Test
  public void clickGameDBLogoToGoToSplashPage() {
    // Test name: click Game-DB Logo To Go To Splash Page
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 973x777 | 
    driver.manage().window().setSize(new Dimension(973, 777));
    // 3 | click | linkText=GameDB | 
    driver.findElement(By.linkText("GameDB")).click();
  }
  @Test
  public void clickOnInDepthStatsLink() {
    // Test name: click On In Depth Stats Link
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 973x777 | 
    driver.manage().window().setSize(new Dimension(973, 777));
    // 3 | click | linkText=Games | 
    driver.findElement(By.linkText("Games")).click();
    // 4 | click | css=.card-deck:nth-child(3) > .card:nth-child(1) .card-img-top | 
    driver.findElement(By.cssSelector(".card-deck:nth-child(3) > .card:nth-child(1) .card-img-top")).click();
    // 5 | click | linkText=In Depth Stats | 
    driver.findElement(By.linkText("In Depth Stats")).click();
  }
  @Test
  public void paginationForDevelopers() {
    // Test name: pagination For Developers
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 973x777 | 
    driver.manage().window().setSize(new Dimension(973, 777));
    // 3 | click | linkText=Developers | 
    driver.findElement(By.linkText("Developers")).click();
    // 4 | click | linkText=2 | 
    driver.findElement(By.linkText("2")).click();
    // 5 | click | linkText=3 | 
    driver.findElement(By.linkText("3")).click();
    // 6 | click | linkText=Next | 
    driver.findElement(By.linkText("Next")).click();
    // 7 | click | linkText=Next | 
    driver.findElement(By.linkText("Next")).click();
    // 8 | click | linkText=8 | 
    driver.findElement(By.linkText("8")).click();
    // 9 | click | linkText=11 | 
    driver.findElement(By.linkText("11")).click();
    // 10 | click | linkText=14 | 
    driver.findElement(By.linkText("14")).click();
    // 11 | click | linkText=17 | 
    driver.findElement(By.linkText("17")).click();
    // 12 | click | linkText=20 | 
    driver.findElement(By.linkText("20")).click();
    // 13 | click | linkText=23 | 
    driver.findElement(By.linkText("23")).click();
  }
  @Test
  public void paginationForGames() {
    // Test name: pagination For Games
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 973x777 | 
    driver.manage().window().setSize(new Dimension(973, 777));
    // 3 | click | linkText=Games | 
    driver.findElement(By.linkText("Games")).click();
    // 4 | click | linkText=2 | 
    driver.findElement(By.linkText("2")).click();
    // 5 | click | linkText=3 | 
    driver.findElement(By.linkText("3")).click();
    // 6 | click | linkText=4 | 
    driver.findElement(By.linkText("4")).click();
    // 7 | click | linkText=7 | 
    driver.findElement(By.linkText("7")).click();
    // 8 | click | linkText=10 | 
    driver.findElement(By.linkText("10")).click();
    // 9 | click | linkText=13 | 
    driver.findElement(By.linkText("13")).click();
    // 10 | click | linkText=16 | 
    driver.findElement(By.linkText("16")).click();
    // 11 | click | linkText=19 | 
    driver.findElement(By.linkText("19")).click();
  }
  @Test
  public void paginationForPublishers() {
    // Test name: pagination For Publishers
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 973x777 | 
    driver.manage().window().setSize(new Dimension(973, 777));
    // 3 | click | linkText=Publishers | 
    driver.findElement(By.linkText("Publishers")).click();
    // 4 | click | linkText=4 | 
    driver.findElement(By.linkText("4")).click();
    // 5 | click | linkText=7 | 
    driver.findElement(By.linkText("7")).click();
    // 6 | click | linkText=10 | 
    driver.findElement(By.linkText("10")).click();
  }
  @Test
  public void submitReview() {
    // Test name: submit Review
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 973x777 | 
    driver.manage().window().setSize(new Dimension(973, 777));
    // 3 | click | linkText=Games | 
    driver.findElement(By.linkText("Games")).click();
    // 4 | click | linkText=See More | 
    driver.findElement(By.linkText("See More")).click();
    // 5 | click | id=title | 
    driver.findElement(By.id("title")).click();
    // 6 | type | id=title | Test Review
    driver.findElement(By.id("title")).sendKeys("Test Review");
    // 7 | click | css=.form-group > #review | 
    driver.findElement(By.cssSelector(".form-group > #review")).click();
    // 8 | type | css=.form-group > #review | Fake review
    driver.findElement(By.cssSelector(".form-group > #review")).sendKeys("Fake review");
    // 9 | click | id=rating5 | 
    driver.findElement(By.id("rating5")).click();
    // 10 | click | css=.btn:nth-child(4) | 
    driver.findElement(By.cssSelector(".btn:nth-child(4)")).click();
  }
}
