// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AllSeleniumTestsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void gamesPublishersNews() {
    // Test name: Games->Publishers->News
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 973x593 | 
    driver.manage().window().setSize(new Dimension(973, 593));
    // 3 | click | linkText=Games | 
    driver.findElement(By.linkText("Games")).click();
    // 4 | click | css=.card-deck:nth-child(3) > .card:nth-child(2) .btn | 
    driver.findElement(By.cssSelector(".card-deck:nth-child(3) > .card:nth-child(2) .btn")).click();
    // 5 | click | linkText=Electronic Arts | 
    driver.findElement(By.linkText("Electronic Arts")).click();
    // 6 | click | linkText=See More | 
    driver.findElement(By.linkText("See More")).click();
    // 7 | click | linkText=See More | 
    driver.findElement(By.linkText("See More")).click();
    // 8 | click | css=.media:nth-child(1) a > .mt-0 | 
    driver.findElement(By.cssSelector(".media:nth-child(1) a > .mt-0")).click();
  }
  @Test
  public void checkAllTabs() {
    // Test name: check All Tabs
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 1300x1500 | 
    driver.manage().window().setSize(new Dimension(1300, 1500));
    // 3 | click | linkText=Home | 
    driver.findElement(By.linkText("Home")).click();
    // 4 | click | linkText=Developers | 
    driver.findElement(By.linkText("Developers")).click();
    // 5 | click | linkText=Publishers | 
    driver.findElement(By.linkText("Publishers")).click();
    // 6 | click | linkText=About | 
    driver.findElement(By.linkText("About")).click();
    // 7 | click | linkText=News | 
    driver.findElement(By.linkText("News")).click();
    // 8 | click | linkText=Games | 
    driver.findElement(By.linkText("Games")).click();
  }
  @Test
  public void gamesPublisherNews() {
    // Test name: games->Publisher->News
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 994x692 | 
    driver.manage().window().setSize(new Dimension(994, 692));
    // 3 | click | linkText=Games | 
    driver.findElement(By.linkText("Games")).click();
    // 4 | click | linkText=See More | 
    driver.findElement(By.linkText("See More")).click();
    // 5 | click | linkText=Rockstar Games | 
    driver.findElement(By.linkText("Rockstar Games")).click();
    // 6 | click | css=.card:nth-child(4) .btn | 
    driver.findElement(By.cssSelector(".card:nth-child(4) .btn")).click();
    // 7 | click | css=.media:nth-child(3) a > .mt-0 | 
    driver.findElement(By.cssSelector(".media:nth-child(3) a > .mt-0")).click();
  }
  @Test
  public void wishlistAddRemoveFirstGameOnGames() {
    // Test name: wishlist Add/Remove First Game On Games 
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | click | linkText=Games | 
    driver.findElement(By.linkText("Games")).click();
    // 3 | click | css=.card-deck:nth-child(3) > .card:nth-child(1) .card-img-top | 
    driver.findElement(By.cssSelector(".card-deck:nth-child(3) > .card:nth-child(1) .card-img-top")).click();
    // 4 | click | css=.btn-secondary | 
    driver.findElement(By.cssSelector(".btn-secondary")).click();
    // 5 | verifyElementPresent | css=.btn-secondary | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".btn-secondary"));
      assert(elements.size() > 0);
    }
    // 6 | click | linkText=Wishlist | 
    driver.findElement(By.linkText("Wishlist")).click();
    // 7 | click | linkText=Remove | 
    driver.findElement(By.linkText("Remove")).click();
  }
}
