// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DoesntMatterIfLoggedInOutTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void aboutGitHubRepoLink() {
    // Test name: about GitHub Repo Link
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | linkText=About | 
    driver.findElement(By.linkText("About")).click();
    // 4 | click | linkText=game-db | 
    driver.findElement(By.linkText("game-db")).click();
  }
  @Test
  public void aboutRAWGLink() {
    // Test name: about RAWG Link
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | linkText=About | 
    driver.findElement(By.linkText("About")).click();
    // 4 | click | linkText=RAWG | 
    driver.findElement(By.linkText("RAWG")).click();
  }
  @Test
  public void aboutTab() {
    // Test name: about Tab
    // Step # | name | target | value
  }
  @Test
  public void clickGameDBLogoToGoToSplashPage() {
    // Test name: click Game-DB Logo To Go To Splash Page
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 973x777 | 
    driver.manage().window().setSize(new Dimension(973, 777));
    // 3 | click | linkText=GameDB | 
    driver.findElement(By.linkText("GameDB")).click();
  }
  @Test
  public void developersGamesSony() {
    // Test name: developers -> Games (Sony)
    // Step # | name | target | value
    // 1 | open | /developer?id=5e7abdffbd80cf188df37652 | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/developer?id=5e7abdffbd80cf188df37652");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | linkText=See More | 
    driver.findElement(By.linkText("See More")).click();
  }
  @Test
  public void developersPublishersSony() {
    // Test name: developers -> Publishers (Sony)
    // Step # | name | target | value
    // 1 | open | /developer?id=5e7abdffbd80cf188df37652 | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/developer?id=5e7abdffbd80cf188df37652");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | css=.card-deck:nth-child(9) > .card:nth-child(1) .btn | 
    driver.findElement(By.cssSelector(".card-deck:nth-child(9) > .card:nth-child(1) .btn")).click();
  }
  @Test
  public void developersClickFirstOne() {
    // Test name: developers Click First One
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | linkText=Developers | 
    driver.findElement(By.linkText("Developers")).click();
    // 4 | click | linkText=See More | 
    driver.findElement(By.linkText("See More")).click();
  }
  @Test
  public void developersTab() {
    // Test name: developers Tab
    // Step # | name | target | value
  }
  @Test
  public void fakeSearchBaralwaysleadstohomepage() {
    // Test name: fake Search Bar (always leads to homepage)
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | css=.form-control | 
    driver.findElement(By.cssSelector(".form-control")).click();
    // 4 | type | css=.form-control | test
    driver.findElement(By.cssSelector(".form-control")).sendKeys("test");
    // 5 | sendKeys | css=.form-control | ${KEY_ENTER}
    driver.findElement(By.cssSelector(".form-control")).sendKeys(Keys.ENTER);
    // 6 | type | css=.form-control | test
    driver.findElement(By.cssSelector(".form-control")).sendKeys("test");
  }
  @Test
  public void gameDBIconLinkToSplashpage() {
    // Test name: gameDB Icon Link To Splashpage
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | linkText=GameDB | 
    driver.findElement(By.linkText("GameDB")).click();
  }
  @Test
  public void gamesDevelopersGTA() {
    // Test name: games -> Developers (GTA)
    // Step # | name | target | value
    // 1 | open | /game?id=5e7ab0b26b5b29159f027d84 | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/game?id=5e7ab0b26b5b29159f027d84");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | linkText=Rockstar Games | 
    driver.findElement(By.linkText("Rockstar Games")).click();
  }
  @Test
  public void gamesPublishersGTA() {
    // Test name: games -> Publishers (GTA)
    // Step # | name | target | value
    // 1 | open | /game?id=5e7ab0b26b5b29159f027d84 | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/game?id=5e7ab0b26b5b29159f027d84");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | css=p:nth-child(5) > a | 
    driver.findElement(By.cssSelector("p:nth-child(5) > a")).click();
  }
  @Test
  public void gamesClickFirstOne() {
    // Test name: games Click First One
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | linkText=Games | 
    driver.findElement(By.linkText("Games")).click();
    // 4 | click | linkText=See More | 
    driver.findElement(By.linkText("See More")).click();
  }
  @Test
  public void gamesTab() {
    // Test name: games Tab
    // Step # | name | target | value
  }
  @Test
  public void homeTab() {
    // Test name: home Tab
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | linkText=Home | 
    driver.findElement(By.linkText("Home")).click();
  }
  @Test
  public void homepageCarousel() {
    // Test name: homepage Carousel
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | linkText=Next | 
    driver.findElement(By.linkText("Next")).click();
    // 4 | click | linkText=Next | 
    driver.findElement(By.linkText("Next")).click();
    // 5 | click | linkText=Next | 
    driver.findElement(By.linkText("Next")).click();
    // 6 | click | linkText=Next | 
    driver.findElement(By.linkText("Next")).click();
    // 7 | click | linkText=Next | 
    driver.findElement(By.linkText("Next")).click();
  }
  @Test
  public void homepageCarouselLinks() {
    // Test name: homepage Carousel Links
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | css=.active .img-fluid | 
    driver.findElement(By.cssSelector(".active .img-fluid")).click();
  }
  @Test
  public void homepageNews() {
    // Test name: homepage News
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | css=.media:nth-child(2) h4 | 
    driver.findElement(By.cssSelector(".media:nth-child(2) h4")).click();
  }
  @Test
  public void homepagePCGames() {
    // Test name: homepage PC Games
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | css=.media:nth-child(5) .media:nth-child(3) h6 | 
    driver.findElement(By.cssSelector(".media:nth-child(5) .media:nth-child(3) h6")).click();
  }
  @Test
  public void homepagePlayStationGames() {
    // Test name: homepage PlayStation Games
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | css=.media:nth-child(8) .media:nth-child(3) h6 | 
    driver.findElement(By.cssSelector(".media:nth-child(8) .media:nth-child(3) h6")).click();
  }
  @Test
  public void homepageSwitchGames() {
    // Test name: homepage Switch Games
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | css=.media:nth-child(2) .media:nth-child(3) h6 | 
    driver.findElement(By.cssSelector(".media:nth-child(2) .media:nth-child(3) h6")).click();
  }
  @Test
  public void homepageXboxGames() {
    // Test name: homepage Xbox Games
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | css=.media:nth-child(11) .media:nth-child(3) h6 | 
    driver.findElement(By.cssSelector(".media:nth-child(11) .media:nth-child(3) h6")).click();
  }
  @Test
  public void newsClickFirstOne() {
    // Test name: news Click First One
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | linkText=News | 
    driver.findElement(By.linkText("News")).click();
    // 4 | click | css=.media:nth-child(1) a > .mt-0 | 
    driver.findElement(By.cssSelector(".media:nth-child(1) a > .mt-0")).click();
  }
  @Test
  public void newsTab() {
    // Test name: news Tab
    // Step # | name | target | value
  }
  @Test
  public void paginationForDevelopers() {
    // Test name: pagination For Developers
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 973x777 | 
    driver.manage().window().setSize(new Dimension(973, 777));
    // 3 | click | linkText=Developers | 
    driver.findElement(By.linkText("Developers")).click();
    // 4 | click | linkText=2 | 
    driver.findElement(By.linkText("2")).click();
    // 5 | click | linkText=3 | 
    driver.findElement(By.linkText("3")).click();
    // 6 | click | linkText=Next | 
    driver.findElement(By.linkText("Next")).click();
    // 7 | click | linkText=Next | 
    driver.findElement(By.linkText("Next")).click();
    // 8 | click | linkText=8 | 
    driver.findElement(By.linkText("8")).click();
    // 9 | click | linkText=11 | 
    driver.findElement(By.linkText("11")).click();
    // 10 | click | linkText=14 | 
    driver.findElement(By.linkText("14")).click();
    // 11 | click | linkText=17 | 
    driver.findElement(By.linkText("17")).click();
    // 12 | click | linkText=20 | 
    driver.findElement(By.linkText("20")).click();
    // 13 | click | linkText=23 | 
    driver.findElement(By.linkText("23")).click();
  }
  @Test
  public void paginationForGames() {
    // Test name: pagination For Games
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 973x777 | 
    driver.manage().window().setSize(new Dimension(973, 777));
    // 3 | click | linkText=Games | 
    driver.findElement(By.linkText("Games")).click();
    // 4 | click | linkText=2 | 
    driver.findElement(By.linkText("2")).click();
    // 5 | click | linkText=3 | 
    driver.findElement(By.linkText("3")).click();
    // 6 | click | linkText=4 | 
    driver.findElement(By.linkText("4")).click();
    // 7 | click | linkText=7 | 
    driver.findElement(By.linkText("7")).click();
    // 8 | click | linkText=10 | 
    driver.findElement(By.linkText("10")).click();
    // 9 | click | linkText=13 | 
    driver.findElement(By.linkText("13")).click();
    // 10 | click | linkText=16 | 
    driver.findElement(By.linkText("16")).click();
    // 11 | click | linkText=19 | 
    driver.findElement(By.linkText("19")).click();
  }
  @Test
  public void paginationForPublishers() {
    // Test name: pagination For Publishers
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 973x777 | 
    driver.manage().window().setSize(new Dimension(973, 777));
    // 3 | click | linkText=Publishers | 
    driver.findElement(By.linkText("Publishers")).click();
    // 4 | click | linkText=4 | 
    driver.findElement(By.linkText("4")).click();
    // 5 | click | linkText=7 | 
    driver.findElement(By.linkText("7")).click();
    // 6 | click | linkText=10 | 
    driver.findElement(By.linkText("10")).click();
  }
  @Test
  public void publishersDevelopersElectronicArts() {
    // Test name: publishers -> Developers (Electronic Arts)
    // Step # | name | target | value
    // 1 | open | /publisher?id=5e7ac43ae4464f1993258e22 | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/publisher?id=5e7ac43ae4464f1993258e22");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | linkText=See More | 
    driver.findElement(By.linkText("See More")).click();
  }
  @Test
  public void publishersGamesElectronicArts() {
    // Test name: publishers -> Games (Electronic Arts)
    // Step # | name | target | value
    // 1 | open | /publisher?id=5e7ac43ae4464f1993258e22 | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/publisher?id=5e7ac43ae4464f1993258e22");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | css=.card-deck:nth-child(9) > .card:nth-child(1) .btn | 
    driver.findElement(By.cssSelector(".card-deck:nth-child(9) > .card:nth-child(1) .btn")).click();
  }
  @Test
  public void publishersClickFirstOne() {
    // Test name: publishers Click First One
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | linkText=Publishers | 
    driver.findElement(By.linkText("Publishers")).click();
    // 4 | click | linkText=See More | 
    driver.findElement(By.linkText("See More")).click();
  }
  @Test
  public void publishersTab() {
    // Test name: publishers Tab
    // Step # | name | target | value
  }
}
