// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SmokeTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void clickAllTabsLoggedOut() {
    // Test name: click All Tabs_(Logged Out)
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | click | linkText=GameDB | 
    driver.findElement(By.linkText("GameDB")).click();
    // 3 | click | linkText=Home | 
    driver.findElement(By.linkText("Home")).click();
    // 4 | click | linkText=Developers | 
    driver.findElement(By.linkText("Developers")).click();
    // 5 | click | linkText=Publishers | 
    driver.findElement(By.linkText("Publishers")).click();
    // 6 | click | linkText=About | 
    driver.findElement(By.linkText("About")).click();
    // 7 | click | linkText=Feeling Curious | 
    driver.findElement(By.linkText("Feeling Curious")).click();
    // 8 | click | linkText=News | 
    driver.findElement(By.linkText("News")).click();
    // 9 | click | linkText=Games | 
    driver.findElement(By.linkText("Games")).click();
  }
  @Test
  public void publishersClickFirstOne() {
    // Test name: publishers Click First One
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | linkText=Publishers | 
    driver.findElement(By.linkText("Publishers")).click();
    // 4 | click | linkText=See More | 
    driver.findElement(By.linkText("See More")).click();
  }
  @Test
  public void newsClickFirstOne() {
    // Test name: news Click First One
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | linkText=News | 
    driver.findElement(By.linkText("News")).click();
    // 4 | click | css=.media:nth-child(1) a > .mt-0 | 
    driver.findElement(By.cssSelector(".media:nth-child(1) a > .mt-0")).click();
  }
  @Test
  public void gamesClickFirstOne() {
    // Test name: games Click First One
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | linkText=Games | 
    driver.findElement(By.linkText("Games")).click();
    // 4 | click | linkText=See More | 
    driver.findElement(By.linkText("See More")).click();
  }
  @Test
  public void developersClickFirstOne() {
    // Test name: developers Click First One
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 1280x800 | 
    driver.manage().window().setSize(new Dimension(1280, 800));
    // 3 | click | linkText=Developers | 
    driver.findElement(By.linkText("Developers")).click();
    // 4 | click | linkText=See More | 
    driver.findElement(By.linkText("See More")).click();
  }
  @Test
  public void feelingCurious() {
    // Test name: feeling Curious
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 1280x777 | 
    driver.manage().window().setSize(new Dimension(1280, 777));
    // 3 | click | linkText=Feeling Curious | 
    driver.findElement(By.linkText("Feeling Curious")).click();
    // 4 | click | linkText=Feeling Curious | 
    driver.findElement(By.linkText("Feeling Curious")).click();
    // 5 | click | linkText=Feeling Curious | 
    driver.findElement(By.linkText("Feeling Curious")).click();
    // 6 | click | linkText=Feeling Curious | 
    driver.findElement(By.linkText("Feeling Curious")).click();
  }
  @Test
  public void toggleDarkMode() {
    // Test name: toggle Dark Mode
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://gamedb.us-east-1.elasticbeanstalk.com/");
    // 2 | setWindowSize | 1280x777 | 
    driver.manage().window().setSize(new Dimension(1280, 777));
    // 3 | click | css=.toggle-off | 
    driver.findElement(By.cssSelector(".toggle-off")).click();
    // 4 | click | css=.toggle-on | 
    driver.findElement(By.cssSelector(".toggle-on")).click();
    // 5 | click | css=.toggle-off | 
    driver.findElement(By.cssSelector(".toggle-off")).click();
    // 6 | click | css=.toggle-on | 
    driver.findElement(By.cssSelector(".toggle-on")).click();
    // 7 | click | css=.toggle-off | 
    driver.findElement(By.cssSelector(".toggle-off")).click();
    // 8 | click | css=.toggle-on | 
    driver.findElement(By.cssSelector(".toggle-on")).click();
  }
}
